add files
skyvar/registration pull request #17
Opened 2023-03-15 11:29 UTC by esterlev23

2023-03-15 11:36 UTC, bdsoha commented
Don't change this now, but for the future, branch names should be `feature/your-feature-name`, The **`feature/`** part is very important.

2023-03-15 11:37 UTC, bdsoha commented
### Few Cleanup Tasks
- [ ] Do not overwrite content on the `main` branch.
- [ ] Move your code into a sub-directory.

### Additions
- [ ] Add a `README.md` describing how to use/install your code.

2023-03-15 11:41 UTC, esterlev23 commented
I did this because that's what I understood from step 3.
https://github.com/skyvar/registration/pull/17#issuecomment-1469843972

2023-03-15 11:43 UTC, bdsoha commented
> I did this because that's what I understood from step 3. [#17 (comment)](https://github.com/skyvar/registration/pull/17#issuecomment-1469843972)

Step 3 only says to change the suffix:
> with a branch named feature/my-task-name (using lower-kabob-case only), replace my-task-name with a short description of your task.

2023-03-15 11:43 UTC, esterlev23 commented
A README.md describing how to use/install I have already added.

2023-03-15 11:45 UTC, bdsoha commented
> A README.md describing how to use/install I have already added.

Then push your changes and mark the check-box as done.

2023-03-15 11:52 UTC, bdsoha commented
**Move your code into a sub-directory.**

Don't overwrite content of the main README.md.

2023-03-15 11:57 UTC, esterlev23 commented
How do i mark the the check-box?
And after the recent changes is it necessary to create a new PR? Or does it sync itself?

2023-03-15 11:59 UTC, bdsoha commented
> How do i mark the the check-box? 
Just click it.

> And after the recent changes is it necessary to create a new PR? Or does it sync itself?
It syncs itself, it would be very inconvenient to have to create a new PR for every change.
You can [click here](https://github.com/skyvar/registration/pull/17/commits) to see the git commit history for this PR.

2023-03-15 12:00 UTC, bdsoha commented
Please refer to this comment for all of your files:
https://github.com/skyvar/registration/pull/17#issuecomment-1469866014

2023-03-15 12:04 UTC, esterlev23 commented
> 



> > How do i mark the the check-box?
> > Just click it.
its diable
> 
> > And after the recent changes is it necessary to create a new PR? Or does it sync itself?
> > It syncs itself, it would be very inconvenient to have to create a new PR for every change.
> > You can [click here](https://github.com/skyvar/registration/pull/17/commits) to see the git commit history for this PR.

2023-03-15 12:26 UTC, bdsoha commented
The original files from the `main` branch are not meant to be moved or changed.

2023-03-15 12:31 UTC, bdsoha commented
> I have not touched any of the `main` branch files

- You removed the original `README.md`
- You moved the original `.github` folder

2023-03-15 12:32 UTC, esterlev23 commented
> ### Few Cleanup Tasks
> * [x]  Do not overwrite content on the `main` branch.
> * [x]  Move your code into a sub-directory.
> 
> ### Additions
> * [x]  Add a `README.md` describing how to use/install your code.

2023-03-15 12:35 UTC, esterlev23 commented
did i finished my task?

2023-03-15 12:37 UTC, bdsoha commented
> did i finished my task?

No, once the PR is in the state it should be, then begins code review.
The issues until now were *naming* and structural.

**Again:** regarding the `README.md`, do not overwrite the `README.md` from the `main` branch.
Include your file in your sub-directory and leave the original file as-is.

2023-03-15 12:56 UTC, bdsoha requested changes

2023-03-15 12:56 UTC, bdsoha commented on app/README.md
> +This project is a FastAPI-based web service for managing user information.
```suggestion
# FastAPI

This project is a FastAPI-based web service for managing user information.
```

2023-03-15 12:56 UTC, bdsoha commented on app/README.md
> +docker run -p 8000:8000 -v /path/to/local/directory:/app myapp
```suggestion
```sh
docker build -t myapp .
docker run -p 8000:8000 -v /path/to/local/directory:/app myapp
```
```

2023-03-15 12:56 UTC, bdsoha commented on app/README.md
> +You can then access the API at http://localhost:8000/docs.
```suggestion
You can then access the API at `http://localhost:8000/docs`.
```

2023-03-15 12:56 UTC, bdsoha commented on app/README.md
> +  - POST /users: Adds a new user to the system.
```suggestion
  - `GET /users`: Returns a list of the 10 most recently added users.
  - `POST /users`: Adds a new user to the system.
```

2023-03-15 12:56 UTC, bdsoha commented on app/README.md
> +This project is licensed under the MIT License - see the LICENSE file for details.
```suggestion
```

2023-03-15 12:56 UTC, bdsoha commented on app/main.py
> +
Can this be shortened?

2023-03-15 12:56 UTC, bdsoha commented on app/main.py
> +    return last_payloads
Can this be inlined?

2023-03-15 12:56 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
What happens after the 11th user is added?

2023-03-15 13:01 UTC, esterlev23 commented
> > did i finished my task?
> 
> No, once the PR is in the state it should be, then begins code review. The issues until now were _naming_ and structural.
> 
> **Again:** regarding the `README.md`, do not overwrite the `README.md` from the `main` branch. Include your file in your sub-directory and leave the original file as-is.
>>I hope I was correct this time.

2023-03-15 13:06 UTC, bdsoha commented
You can now move on to resolve the various review points posted in the conversation above.
Some of them are as simple as clicking *commit suggestion*.

2023-03-16 06:13 UTC, bdsoha commented on app/main.py
> +@app.post("/addUser")
```suggestion
@app.post("/users")
```

2023-03-16 09:03 UTC, bdsoha commented on app/main.py
> +
Not what I meant.
Feel free to discuss the comment before making changes,

2023-03-16 09:05 UTC, bdsoha commented on app/main.py
> +
You are receiving an object of type `User(BaseModel)`. 
I would assume that they have either ability to:
- Cast: `dict(obj)`
- Convert: `obj.dict()`

2023-03-16 09:15 UTC, esterlev23 commented on app/main.py
> +
I will try this way.
I'm glad to know a shorter way.
(I haven't worked enough with Python so I need to grub a little more...)

2023-03-16 10:07 UTC, esterlev23 commented on app/main.py
> +
I changed the code but when I run I don't see the changes. Do I need to create a new image?

2023-03-16 10:08 UTC, bdsoha commented on app/main.py
> +
Your image is _sealed_ with the code from when it was built.
So yes, you need to rebuild.

2023-03-16 10:33 UTC, esterlev23 commented on app/main.py
> +
i changed it

2023-03-16 11:14 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
the file wil contain 21 users.

2023-03-16 11:56 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
You are storing data *in-memory* and *on-disk* at the same time.
Every time a new entry is added you will reach an `n + 1` problem.

2023-03-16 12:03 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
I'm trying to solve it.
I tried to add the user directly to the file,
But then i got syntext error in the JSON data file.

2023-03-16 12:21 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
Before you try and solve something based on a comment I mentioned, please discuss it.
It will save you time.

Does it make sense to maintain a file in such a format?

2023-03-16 12:23 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
Remember, this entire assignment is a learning experience.

2023-03-16 12:31 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
Undoubtedly, I learned and am still learning a lot from the assignment, mainly working with Git, Docker and writing correctly in Python.

In any case, it does not make sense, because what will happen when there is a lot of data its will take up a lot of unnecessary space!

2023-03-16 12:57 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
That's why I thought that maybe I could give up the list of users and insert every object directly into the file.
In JavaScript for example, I would do this a lot:
 Imports the array from the Json file and push into him obj.
Can I do it in Python too?
Is this the right way?

2023-03-16 14:05 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
> That's why I thought that maybe I could give up the list of users and insert every object directly into the file. In JavaScript for example, I would do this a lot: Imports the array from the Json file and push into him obj. Can I do it in Python too? Is this the right way?

A programming language is just a tool, you can do everything in every language.
The `n+1` and memory issue also exists in JavaScript.

I have the following suggestions:
- Only keep the last 10 users in memory and the rest in disk. In such a case, you will not need to open the file on _reads_.
- You can persist the data to disk in one of two ways:
  1. Append the _full_ `json` object as a row to the end of the file, this is called `jsonl`. Meaning, each line contains a full object and is not stored as an indexed array.
  2. Create rolling files for every 100 *(or 1000)* objects added. For example, the first file will be called `data.0.json`, and the next one `data.1.json`.

**Do not implement the above mentioned suggested, I just want to make sure you understand them.**

2023-03-19 05:35 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
I understood.

> Create rolling files for every 100 (or 1000) objects added. For example, the first file will be called data.0.json, and the next one data.1.json.

What problem does it solve?

2023-03-19 05:45 UTC, esterlev23 commented on app/main.py
> +    return last_payloads
for sure,
I thought that way it was clearer what the function returns.

2023-03-19 05:53 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
By creating a *rolling* data file, you are always opening/closing a file that contains no more then `x` rows. Therefore, the `n+1` problem becomes `min(x, n+1)`.

To make sure that you understood, please response with a sample `data.jsonl` file.

2023-03-19 06:15 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
_Writing to the file function:_

> async def add_user(user:User):
    with open("data.json","a") as f:
       json.dump(dict(user), f)
       f.write("\n")
    return {"message": "Payload added successfully"}

2023-03-19 06:18 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
I  was referring to the actual output of the `jsonl` file.

2023-03-19 06:28 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
{"id": 123456789, "name": "Ester"}
{"id": 123456789, "name": "Ester"}
{"id": 123456789, "name": "Ester"}
{"id": 123456789, "name": "Ester"}
{"id": 123456789, "name": "Ester"}

2023-03-19 06:33 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
Does `jsonl` needs a special installation?

2023-03-19 06:35 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
No special install if you want to read/write manually *(always appending new entries to the EOF)*.
It does require a special install if you want to utilize tooling to handle the read/parse.

`jsonl` would solve the `n+1` problem.

2023-03-19 07:11 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
I learned וn Google about `jsonl`:
writing and reading etc.
Should I change it in my assignment?

2023-03-19 07:20 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
No, I just wanted to make sure your understood.
I am also very pleased that you asked and didn't jump to implementation.

2023-03-19 07:23 UTC, bdsoha commented
Before I close this PR,
How would you test your code at the unit level?
The `http` *(input/output)* layer and the `data` layer are tightly-coupled.
*Do not implement, only provide a response*.

2023-03-19 07:25 UTC, esterlev23 commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
so what now?

2023-03-19 07:27 UTC, bdsoha commented on app/main.py
> +        json.dump([user_to_dict(user) for user in users], f)
> so what now?

I wrote a comment https://github.com/skyvar/registration/pull/17#issuecomment-1475135329

2023-03-19 07:56 UTC, esterlev23 commented
> Before I close this PR, How would you test your code at the unit level? The `http` _(input/output)_ layer and the `data` layer are tightly-coupled. _Do not implement, only provide a response_.

I didn't quite understand the question.
Can you please give me more details?

2023-03-19 08:00 UTC, esterlev23 commented
I ran the image in Docker.
I entered data through the swagger,
I also got a refund through Swagger.
If I got an error response back,
I went into the files in the container,
And I checked there how the data was entered? in what format etc.

2023-03-19 08:12 UTC, bdsoha commented
> I ran the image in Docker. I entered data through the swagger, I also got a refund through Swagger. If I got an error response back, I went into the files in the container, And I checked there how the data was entered? in what format etc.

I am referring to automated _unit testing_.
Since your code is tightly-coupled, your test cases would be forced to use `http` calls in order to verify functionality.
It is best practice to separate code into multiple layers.

![architecture-diagram-1024x763](https://user-images.githubusercontent.com/4192777/226162302-450646c4-e45c-4ae5-a468-775377c8a7df.png)

2023-03-19 08:29 UTC, esterlev23 commented
The truth is that until today I only worked with separation into layers.
I wrote in Node and Dot Net,
But this time the server is so thin, so it didn't occur to me to separate...
I have no doubt that this is indeed the way!

2023-03-19 08:31 UTC, bdsoha commented
> The truth is that until today I only worked with separation into layers. I wrote in Node and Dot Net, But this time the server is so thin, so it didn't occur to me to separate... I have no doubt that this is indeed the way!

The same _architectural_ layering can be found in those languages as well.
It is also agnostic to:
- http
- cli
- client/server
- standalone ui

2023-03-19 08:32 UTC, merged

2023-03-19 08:32 UTC, bdsoha commented
**🎉 Congrats on your first merged PR.**

You will soon be added as a collaborator to this repo.
In the meantime, please prepare a short presentation *(in English)* describing:

- The task in general.
- Things you learned along the way.
- Tips for other team-members for future tasks.

2023-03-20 07:05 UTC, bdsoha commented
You have been sent an email invitation to the [SkyVar Organization](https://github.com/skyvar).
Please open your cooperate email and finish the registration process.