Check password strength
skyvar/registration pull request #26
Opened 2023-03-16 09:59 UTC by FridaPshitik

Write a function that checks that each received password will be correct according to certain criteria

Closes #4

2023-03-16 10:01 UTC, bdsoha commented
- [ ] Move your code into a sub-directory so that it shouldn't conflict with others.
- [ ] Add a readme to the sub-directory explaining how to install/use your code.

2023-03-16 12:23 UTC, bdsoha commented
Please change the directory name to something more significant, like `password-strength`.

2023-03-19 05:43 UTC, bdsoha commented
I will begin the code review now.

2023-03-19 05:48 UTC, bdsoha requested changes

2023-03-19 05:48 UTC, bdsoha commented on password-strength/README.md
> +Password Strength Checker
```suggestion
# Password Strength Checker
```

2023-03-19 05:48 UTC, bdsoha commented on password-strength/README.md
> +This project is licensed under the MIT License - see the LICENSE file for details.
How and why are you licensing your code?
```suggestion
```

2023-03-19 05:48 UTC, bdsoha commented on password-strength/dockerfile
> +FROM node:16.19.1-buster
```suggestion
FROM node:16.19.1-buster
```

2023-03-19 05:48 UTC, bdsoha commented on password-strength/dockerfile
> +WORKDIR /passwordString
Do you need to set a `WORKDIR`?

2023-03-19 05:49 UTC, bdsoha requested changes

2023-03-19 05:49 UTC, bdsoha commented on password-strength/app.js
> +    return false;
```suggestion
    return isLowerCharacter(password) 
        && isUpperCharacter(password)
        && isDigit(password)
        && isSpecialCharacter(password)
        && isLength(password)
        && isRepeatMoreThanTwice(password)
        && isSequencesOfThree(password)
```

2023-03-19 05:50 UTC, bdsoha commented
### Few Questions
- What are the any advantages and disadvantages of using `regex`?
- How would OOP assist in abstracting the code?
- Can you test the current implementation at the _unit_ level?

2023-03-19 07:15 UTC, FridaPshitik commented
Is this the OOP usage you meant?

2023-03-19 07:19 UTC, bdsoha commented
> * How would OOP assist in abstracting the code?

I didn't ask you to implement, I just asked you *How would you*.
It is important to pay attention to the small details, it saves time, and ⌚is 💲

2023-03-19 07:34 UTC, FridaPshitik commented
Using OOP you can put all password handling functions under one roof
In my opinion the current task does not have a critical need for OOP

2023-03-19 07:44 UTC, bdsoha commented
> Using OOP you can put all password handling functions under one roof In my opinion the current task does not have a critical need for OOP

You opinion is noted, IMO, there is a very strong case for OOP.
Using OOP you would be able to:
- Remove all `if` statements.
- Abstractly handle character conversions.
- Unit test specific rules.
- Dynamically disable rule checking.
- Log flow messages *(debug)*.


```js
class AbstractBaseRule {
    _handle(password) {
        if (this.check(password)) {
            // ...
        }
    }

    check(password) {
        throw new Error('Abstract non-implemented method');
    }
}
```

2023-03-19 07:59 UTC, FridaPshitik commented
Do you mean all the IF's were in one function

2023-03-19 08:07 UTC, bdsoha commented
> Do you mean all the IF's were in one function

Based on the code I provided the inherited rule would look like this:

```js
class HasLowerCase extends AbstractBaseRule {
    check(password) {
        return /[a-z]/.test(password)
    }
}
```

This can be individually tested and extendable.

2023-03-19 09:02 UTC, FridaPshitik commented
REJEX is a useful mechanism for identifying and filtering different types of data
The advantages of REJEX are:

1. Time reduction - the use of REJEX may save a lot of time in the implementation and filtering of the data, so that the user can act faster and save valuable time.
2. Accuracy - REJEX makes it possible to identify the data in a more efficient way and thus avoid mistakes and also get more accurate results.
3. Flexibility - REJEX can be adapted to a wide variety of data,

The disadvantages of REJEX are:

1. REJEX must be correct in the implementation and definition of the templates, so if the template is wrong or inaccurate, the user may miss important data or get inaccurate results.
2. REJEX commands are more complex to learn

Since the pros outweigh the cons, I'm in the middle of switching to using rejex

2023-03-19 12:04 UTC, FridaPshitik commented
class HasRepeatMoreThanTwice extends AbstractBaseRule {
    check(password) {
        let pass = /([a-zA-Z0-9])\1{2,}/
        return pass.test(password)
    }
}

Do you know why this function is not working?
I try many ways and nothing works

2023-03-19 12:06 UTC, bdsoha commented
> class HasRepeatMoreThanTwice extends AbstractBaseRule { check(password) { let pass = /([a-zA-Z0-9])\1{2,}/ return pass.test(password) } }
> 
> Do you know why this function is not working? I try many ways and nothing works

Assuming the `AbstractBaseRule` exists:
```js
new HasRepeatMoreThanTwice().check('someteststring')
```

2023-03-19 12:33 UTC, bdsoha commented
Don't change the code again.
Pay attention to what was written [here](https://github.com/skyvar/registration/pull/26#issuecomment-1475134458).

This assignment is a learning experience, the fact that I ask you a question doesn't mean "go implement this... or change that...".

2023-03-19 13:06 UTC, FridaPshitik commented
The disadvantages and advantages of using regex
I have already registered
You explained to me how OOP will help simplify the code
And in the usual way that I wrote down, it can be more complicated to check edge cases
But now the code works in all modes I fixed a small mistake

2023-03-19 13:09 UTC, bdsoha commented
**🎉 Congrats on your first merged PR.**

You will soon be added as a collaborator to this repo.
In the meantime, please prepare a short presentation *(in English)* describing:

- The task in general.
- Things you learned along the way.
- Tips for other team-members for future tasks.

2023-03-19 13:09 UTC, merged

2023-03-20 07:05 UTC, bdsoha commented
You have been sent an email invitation to the [SkyVar Organization](https://github.com/skyvar).
Please open your cooperate email and finish the registration process.